import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import { PrismaClient } from '@prisma/client';
import { z } from 'zod';

const app = express();
const prisma = new PrismaClient();
app.use(helmet());
const configured = (process.env.FRONTEND_URL || '').split(',').map(x => x.trim().replace(/\/$/, '')).filter(Boolean);
const allowed = new Set([...configured, 'https://procurement.vaqutecalifornia.com','https://vaqutecalifornia.com','https://www.vaqutecalifornia.com','https://darkmoonknight.github.io']);
app.use(cors({ origin: (origin, cb) => cb(null, !origin || allowed.has('*') || allowed.has(origin?.replace(/\/$/, ''))), credentials: true }));
app.use(express.json({limit:'6mb'}));

const auth=(req,res,next)=>{const t=req.headers.authorization?.replace(/^Bearer\s+/i,'');if(!t)return res.status(401).json({error:'Authentication required'});try{req.user=jwt.verify(t,process.env.JWT_SECRET);next()}catch{return res.status(401).json({error:'Invalid or expired token'})}};
const companyScope=(req,res,next)=>req.user?.companyId?next():res.status(403).json({error:'Company scope missing'});
const role=(...roles)=>(req,res,next)=>roles.includes(req.user?.role)||req.user?.role==='ADMIN'?next():res.status(403).json({error:'Permission denied'});
const num=v=>Number(v||0);
const dateOnly=v=>{const d=new Date(v);d.setHours(0,0,0,0);return d};
const sign=user=>jwt.sign({userId:user.id,companyId:user.companyId,role:user.role,email:user.email},process.env.JWT_SECRET,{expiresIn:process.env.JWT_EXPIRES_IN||'12h'});
async function audit(req,action,entityType,entityId,before=null,after=null){try{await prisma.auditLog.create({data:{companyId:req.user.companyId,userId:req.user.userId,action,entityType,entityId,beforeJson:before?JSON.stringify(before):null,afterJson:after?JSON.stringify(after):null,ipAddress:req.ip}})}catch(e){console.error('audit',e.message)}}
const safeUser=u=>({id:u.id,name:u.name,email:u.email,role:u.role,active:u.active,departmentId:u.departmentId,department:u.department?.name||'Owner / Administration',companyId:u.companyId});

app.get('/',(_q,res)=>res.json({ok:true,service:'ezyprocure-api',version:'3.0.0',status:'online'}));
app.get('/health',async(_q,res)=>{try{await prisma.$queryRaw`SELECT 1`;res.json({ok:true,service:'ezyprocure-api',database:'connected',version:'3.0.0'})}catch{res.status(503).json({ok:false,database:'unavailable'})}});
app.get('/api/health',async(_q,res)=>{try{await prisma.$queryRaw`SELECT 1`;res.json({ok:true,service:'ezyprocure-api',database:'connected',version:'3.0.0'})}catch{res.status(503).json({ok:false,database:'unavailable'})}});

app.post('/api/auth/login',async(req,res,next)=>{try{const x=z.object({email:z.string().email(),password:z.string().min(1)}).parse(req.body);const u=await prisma.user.findUnique({where:{email:x.email.toLowerCase()},include:{company:true,department:true}});if(!u||!u.active||!(await bcrypt.compare(x.password,u.passwordHash)))return res.status(401).json({error:'Invalid email or password'});res.json({token:sign(u),user:safeUser(u),company:{id:u.company.id,name:u.company.name}})}catch(e){next(e)}});
app.get('/api/auth/me',auth,companyScope,async(req,res,next)=>{try{const u=await prisma.user.findFirst({where:{id:req.user.userId,companyId:req.user.companyId,active:true},include:{company:true,department:true}});if(!u)return res.status(401).json({error:'User not found'});res.json({...safeUser(u),company:u.company.name})}catch(e){next(e)}});
app.put('/api/auth/me',auth,companyScope,async(req,res,next)=>{try{const x=z.object({name:z.string().min(2).max(120),email:z.string().email()}).parse(req.body);const exists=await prisma.user.findFirst({where:{email:x.email.toLowerCase(),id:{not:req.user.userId}}});if(exists)return res.status(409).json({error:'Email already in use'});const u=await prisma.user.update({where:{id:req.user.userId},data:{name:x.name,email:x.email.toLowerCase()},include:{department:true}});await audit(req,'UPDATE','User',u.id,null,u);res.json(safeUser(u))}catch(e){next(e)}});
app.put('/api/auth/change-password',auth,companyScope,async(req,res,next)=>{try{const x=z.object({currentPassword:z.string().min(1),newPassword:z.string().min(10).max(100),confirmPassword:z.string().min(10)}).parse(req.body);if(x.newPassword!==x.confirmPassword)return res.status(400).json({error:'New passwords do not match'});const u=await prisma.user.findUnique({where:{id:req.user.userId}});if(!u||!(await bcrypt.compare(x.currentPassword,u.passwordHash)))return res.status(400).json({error:'Current password is incorrect'});const hash=await bcrypt.hash(x.newPassword,12);await prisma.user.update({where:{id:u.id},data:{passwordHash:hash}});await audit(req,'PASSWORD_CHANGE','User',u.id);res.json({ok:true,message:'Password changed successfully'})}catch(e){next(e)}});

const permissions={ADMIN:['*'],MANAGEMENT:['dashboard','reports','approvals','sites','materials','vendors','procurement','accounts','hr','site','tasks','settings'],PROCUREMENT:['dashboard','sites','materials','vendors','procurement','reports'],ACCOUNTS:['dashboard','vendors','accounts','reports','approvals'],HR:['dashboard','hr','reports'],SITE_ENGINEER:['dashboard','site','sites','materials','tasks','reports'],SITE_STORE:['dashboard','site','sites','materials','reports']};
app.get('/api/me/permissions',auth,companyScope,(req,res)=>res.json({role:req.user.role,permissions:permissions[req.user.role]||[]}));

app.get('/api/dashboard',auth,companyScope,async(req,res,next)=>{try{const c=req.user.companyId;const [prs,rfqs,pos,grns,mrns,inv,vendors,employees,labour,expenses,tasks]=await Promise.all([prisma.purchaseRequisition.count({where:{companyId:c,status:{in:['DRAFT','PENDING']}}}),prisma.rFQ.count({where:{companyId:c,status:{in:['DRAFT','SENT']}}}),prisma.purchaseOrder.count({where:{companyId:c,status:{in:['DRAFT','APPROVED','SENT','PARTIAL']}}}),prisma.gRN.count({where:{companyId:c,status:{in:['DRAFT','APPROVED']}}}),prisma.mRN.count({where:{companyId:c,status:{in:['DRAFT','PENDING','APPROVED']}}}),prisma.invoice.count({where:{companyId:c,status:{in:['PENDING','PARTIAL']}}}),prisma.vendor.count({where:{companyId:c,active:true}}),prisma.employee.count({where:{companyId:c,active:true}}),prisma.labour.count({where:{companyId:c,active:true}}),prisma.expense.aggregate({where:{companyId:c},_sum:{amount:true}}),prisma.siteTask.count({where:{companyId:c,status:{in:['PENDING','APPROVED']}}})]);res.json({pendingPR:prs,pendingRFQ:rfqs,openPO:pos,openGRN:grns,pendingMRN:mrns,pendingInvoices:inv,activeVendors:vendors,employees,activeLabour:labour,totalExpenses:num(expenses._sum.amount),openTasks:tasks})}catch(e){next(e)}});

app.get('/api/settings',auth,companyScope,async(req,res,next)=>{try{const c=await prisma.company.findUnique({where:{id:req.user.companyId}});res.json({company:{id:c.id,name:c.name,gstin:c.gstin,countryCode:c.countryCode,baseCurrency:c.baseCurrency,timezone:c.timezone}})}catch(e){next(e)}});
app.put('/api/settings',auth,companyScope,role('ADMIN','MANAGEMENT'),async(req,res,next)=>{try{const x=z.object({name:z.string().min(2).max(120),gstin:z.string().max(30).optional().or(z.literal('')),countryCode:z.string().min(2).max(3),baseCurrency:z.string().min(3).max(5),timezone:z.string().min(3).max(80)}).parse(req.body);const c=await prisma.company.update({where:{id:req.user.companyId},data:{name:x.name,gstin:x.gstin||null,countryCode:x.countryCode,baseCurrency:x.baseCurrency,timezone:x.timezone}});await audit(req,'UPDATE','Company',c.id,null,c);res.json({company:c})}catch(e){next(e)}});

app.get('/api/departments',auth,companyScope,async(req,res,next)=>{try{res.json(await prisma.department.findMany({where:{companyId:req.user.companyId,active:true},orderBy:{name:'asc'}}))}catch(e){next(e)}});
app.get('/api/users',auth,companyScope,role('ADMIN','MANAGEMENT'),async(req,res,next)=>{try{res.json(await prisma.user.findMany({where:{companyId:req.user.companyId},include:{department:true},orderBy:{name:'asc'}}).then(xs=>xs.map(safeUser)))}catch(e){next(e)}});
app.post('/api/users',auth,companyScope,role('ADMIN'),async(req,res,next)=>{try{const x=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(10),role:z.enum(['ADMIN','PROCUREMENT','SITE_STORE','SITE_ENGINEER','ACCOUNTS','HR','MANAGEMENT']),departmentId:z.string().optional()}).parse(req.body);const hash=await bcrypt.hash(x.password,12);const u=await prisma.user.create({data:{companyId:req.user.companyId,name:x.name,email:x.email.toLowerCase(),passwordHash:hash,role:x.role,departmentId:x.departmentId||null},include:{department:true}});await audit(req,'CREATE','User',u.id,null,u);res.status(201).json(safeUser(u))}catch(e){next(e)}});
app.patch('/api/users/:id',auth,companyScope,role('ADMIN'),async(req,res,next)=>{try{const x=z.object({name:z.string().min(2).optional(),email:z.string().email().optional(),role:z.enum(['ADMIN','PROCUREMENT','SITE_STORE','SITE_ENGINEER','ACCOUNTS','HR','MANAGEMENT']).optional(),departmentId:z.string().nullable().optional(),active:z.boolean().optional()}).parse(req.body);const u=await prisma.user.findFirst({where:{id:req.params.id,companyId:req.user.companyId}});if(!u)return res.status(404).json({error:'User not found'});const out=await prisma.user.update({where:{id:u.id},data:x,include:{department:true}});await audit(req,'UPDATE','User',u.id,u,out);res.json(safeUser(out))}catch(e){next(e)}});
app.post('/api/users/:id/reset-password',auth,companyScope,role('ADMIN'),async(req,res,next)=>{try{const x=z.object({password:z.string().min(10)}).parse(req.body);const u=await prisma.user.findFirst({where:{id:req.params.id,companyId:req.user.companyId}});if(!u)return res.status(404).json({error:'User not found'});await prisma.user.update({where:{id:u.id},data:{passwordHash:await bcrypt.hash(x.password,12)}});await audit(req,'RESET_PASSWORD','User',u.id);res.json({ok:true})}catch(e){next(e)}});

const crud=(path,model,include,readRole,createSchema,updateSchema,makeData)=>{
 app.get('/api/'+path,auth,companyScope,readRole?role(...readRole):(_q,_r,n)=>n(),async(req,res,next)=>{try{const where={companyId:req.user.companyId};res.json(await prisma[model].findMany({where,...(include?{include}:{}),orderBy:{name:'asc'}}))}catch(e){next(e)}});
 if(createSchema)app.post('/api/'+path,auth,companyScope,role('ADMIN',...(readRole||[])),async(req,res,next)=>{try{const x=createSchema.parse(req.body);const row=await prisma[model].create({data:{...makeData(x,req),companyId:req.user.companyId},...(include?{include}:{})});await audit(req,'CREATE',model,row.id,null,row);res.status(201).json(row)}catch(e){next(e)}});
 if(updateSchema)app.patch('/api/'+path+'/:id',auth,companyScope,role('ADMIN',...(readRole||[])),async(req,res,next)=>{try{const x=updateSchema.parse(req.body);const old=await prisma[model].findFirst({where:{id:req.params.id,companyId:req.user.companyId}});if(!old)return res.status(404).json({error:'Record not found'});const row=await prisma[model].update({where:{id:old.id},data:x,...(include?{include}:{})});await audit(req,'UPDATE',model,row.id,old,row);res.json(row)}catch(e){next(e)}});
};
crud('sites','site',null,['SITE_ENGINEER','MANAGEMENT'],z.object({code:z.string().min(2),name:z.string().min(2),location:z.string().optional(),manager:z.string().optional()}),z.object({code:z.string().min(2).optional(),name:z.string().min(2).optional(),location:z.string().optional(),manager:z.string().optional(),active:z.boolean().optional()}),x=>x);
crud('materials','material',null,['PROCUREMENT','SITE_ENGINEER','SITE_STORE','MANAGEMENT'],z.object({code:z.string().min(2),name:z.string().min(2),category:z.string().min(1),unit:z.string().min(1),hsn:z.string().optional(),gstRate:z.coerce.number().nonnegative().optional(),reorderLevel:z.coerce.number().nonnegative().optional()}),z.object({code:z.string().min(2).optional(),name:z.string().min(2).optional(),category:z.string().optional(),unit:z.string().optional(),hsn:z.string().optional(),gstRate:z.coerce.number().nonnegative().optional(),reorderLevel:z.coerce.number().nonnegative().optional(),active:z.boolean().optional()}),x=>x);
crud('vendors','vendor',null,['PROCUREMENT','ACCOUNTS','MANAGEMENT'],z.object({name:z.string().min(2),gstin:z.string().optional(),pan:z.string().optional(),phone:z.string().optional(),email:z.string().email().optional().or(z.literal('')),paymentDays:z.coerce.number().int().nonnegative().default(0),creditLimit:z.coerce.number().nonnegative().optional(),rating:z.coerce.number().min(0).max(5).optional()}),z.object({name:z.string().min(2).optional(),gstin:z.string().optional(),pan:z.string().optional(),phone:z.string().optional(),email:z.string().email().optional().or(z.literal('')),paymentDays:z.coerce.number().int().nonnegative().optional(),creditLimit:z.coerce.number().nonnegative().optional(),rating:z.coerce.number().min(0).max(5).optional(),active:z.boolean().optional()}),x=>({...x,email:x.email||null}));

app.get('/api/employees',auth,companyScope,role('HR','MANAGEMENT'),async(req,res,next)=>{try{res.json(await prisma.employee.findMany({where:{companyId:req.user.companyId},include:{department:true},orderBy:{name:'asc'}}))}catch(e){next(e)}});
app.post('/api/employees',auth,companyScope,role('HR'),async(req,res,next)=>{try{const x=z.object({employeeCode:z.string(),name:z.string().min(2),email:z.string().email().optional().or(z.literal('')),phone:z.string().optional(),designation:z.string().optional(),departmentId:z.string().optional(),employmentType:z.string().default('FULL_TIME'),salary:z.coerce.number().nonnegative().optional(),joiningDate:z.coerce.date().optional()}).parse(req.body);const r=await prisma.employee.create({data:{...x,companyId:req.user.companyId,email:x.email||null}});await audit(req,'CREATE','Employee',r.id,null,r);res.status(201).json(r)}catch(e){next(e)}});
app.patch('/api/employees/:id',auth,companyScope,role('HR'),async(req,res,next)=>{try{const x=z.object({employeeCode:z.string().optional(),name:z.string().min(2).optional(),email:z.string().email().optional().or(z.literal('')),phone:z.string().optional(),designation:z.string().optional(),departmentId:z.string().nullable().optional(),employmentType:z.string().optional(),salary:z.coerce.number().nonnegative().optional(),joiningDate:z.coerce.date().optional(),active:z.boolean().optional()}).parse(req.body);const r=await prisma.employee.update({where:{id:req.params.id},data:{...x,email:x.email===''?null:x.email}});await audit(req,'UPDATE','Employee',r.id,null,r);res.json(r)}catch(e){next(e)}});
app.get('/api/labour',auth,companyScope,role('HR','SITE_ENGINEER','SITE_STORE','MANAGEMENT'),async(req,res,next)=>{try{res.json(await prisma.labour.findMany({where:{companyId:req.user.companyId},orderBy:{name:'asc'}}))}catch(e){next(e)}});
app.post('/api/labour',auth,companyScope,role('HR','SITE_STORE'),async(req,res,next)=>{try{const x=z.object({labourCode:z.string(),name:z.string().min(2),trade:z.string().optional(),contractor:z.string().optional(),phone:z.string().optional(),dailyRate:z.coerce.number().nonnegative().optional()}).parse(req.body);const r=await prisma.labour.create({data:{...x,companyId:req.user.companyId}});await audit(req,'CREATE','Labour',r.id,null,r);res.status(201).json(r)}catch(e){next(e)}});
app.patch('/api/labour/:id',auth,companyScope,role('HR','SITE_STORE'),async(req,res,next)=>{try{const x=z.object({labourCode:z.string().optional(),name:z.string().min(2).optional(),trade:z.string().optional(),contractor:z.string().optional(),phone:z.string().optional(),dailyRate:z.coerce.number().nonnegative().optional(),active:z.boolean().optional()}).parse(req.body);const r=await prisma.labour.update({where:{id:req.params.id},data:x});await audit(req,'UPDATE','Labour',r.id,null,r);res.json(r)}catch(e){next(e)}});

const prSchema=z.object({siteId:z.string(),requestedBy:z.string().min(1),requiredDate:z.coerce.date(),notes:z.string().optional(),items:z.array(z.object({materialId:z.string(),quantity:z.coerce.number().positive(),estimatedRate:z.coerce.number().nonnegative().optional()})).min(1)});
app.get('/api/pr',auth,companyScope,async(req,res,next)=>{try{res.json(await prisma.purchaseRequisition.findMany({where:{companyId:req.user.companyId},include:{items:{include:{material:true}},site:true},orderBy:{createdAt:'desc'}}))}catch(e){next(e)}});
app.post('/api/pr',auth,companyScope,role('PROCUREMENT','SITE_ENGINEER','SITE_STORE'),async(req,res,next)=>{try{const x=prSchema.parse(req.body);const site=await prisma.site.findFirst({where:{id:x.siteId,companyId:req.user.companyId,active:true}});if(!site)return res.status(400).json({error:'Invalid site'});const r=await prisma.purchaseRequisition.create({data:{...x,companyId:req.user.companyId,number:`PR-${new Date().getFullYear()}-${Date.now().toString().slice(-7)}`,status:'PENDING',items:{create:x.items}},include:{items:true,site:true}});await audit(req,'CREATE','PurchaseRequisition',r.id,null,r);res.status(201).json(r)}catch(e){next(e)}});
app.patch('/api/pr/:id',auth,companyScope,role('PROCUREMENT'),async(req,res,next)=>{try{const x=z.object({status:z.enum(['DRAFT','PENDING','APPROVED','REJECTED','CANCELLED']).optional(),notes:z.string().optional()}).parse(req.body);const r=await prisma.purchaseRequisition.updateMany({where:{id:req.params.id,companyId:req.user.companyId},data:x});res.json(r)}catch(e){next(e)}});

app.get('/api/rfq',auth,companyScope,async(req,res,next)=>{try{res.json(await prisma.rFQ.findMany({where:{companyId:req.user.companyId},include:{pr:true,vendors:{include:{vendor:true}},quotes:{include:{vendor:true,items:true}}},orderBy:{dueDate:'asc'}}))}catch(e){next(e)}});
app.post('/api/rfq',auth,companyScope,role('PROCUREMENT'),async(req,res,next)=>{try{const x=z.object({prId:z.string(),dueDate:z.coerce.date(),vendorIds:z.array(z.string()).min(1)}).parse(req.body);const pr=await prisma.purchaseRequisition.findFirst({where:{id:x.prId,companyId:req.user.companyId}});if(!pr)return res.status(404).json({error:'PR not found'});const vs=await prisma.vendor.findMany({where:{id:{in:x.vendorIds},companyId:req.user.companyId,active:true}});const r=await prisma.rFQ.create({data:{companyId:req.user.companyId,prId:pr.id,number:`RFQ-${new Date().getFullYear()}-${Date.now().toString().slice(-7)}`,dueDate:x.dueDate,status:'SENT',vendors:{create:vs.map(v=>({vendorId:v.id}))}},include:{vendors:{include:{vendor:true}},pr:true}});await prisma.purchaseRequisition.update({where:{id:pr.id},data:{status:'APPROVED'}});await audit(req,'CREATE','RFQ',r.id,null,r);res.status(201).json(r)}catch(e){next(e)}});
app.get('/api/quotes',auth,companyScope,async(req,res,next)=>{try{res.json(await prisma.quote.findMany({where:{rfq:{companyId:req.user.companyId}},include:{vendor:true,rfq:true,items:{include:{material:true}}},orderBy:{total:'asc'}}))}catch(e){next(e)}});
app.post('/api/quotes',auth,companyScope,role('PROCUREMENT'),async(req,res,next)=>{try{const x=z.object({rfqId:z.string(),vendorId:z.string(),quoteNo:z.string().optional(),freight:z.coerce.number().nonnegative().default(0),tax:z.coerce.number().nonnegative().default(0),validUntil:z.coerce.date().optional(),items:z.array(z.object({materialId:z.string(),quantity:z.coerce.number().positive(),unitRate:z.coerce.number().nonnegative()})).min(1)}).parse(req.body);const r=await prisma.rFQ.findFirst({where:{id:x.rfqId,companyId:req.user.companyId}});const v=await prisma.vendor.findFirst({where:{id:x.vendorId,companyId:req.user.companyId}});if(!r||!v)return res.status(404).json({error:'RFQ or vendor not found'});const total=x.items.reduce((s,i)=>s+i.quantity*i.unitRate,0)+x.freight+x.tax;res.status(201).json(await prisma.quote.create({data:{rfqId:r.id,vendorId:v.id,quoteNo:x.quoteNo,freight:x.freight,tax:x.tax,validUntil:x.validUntil,total,items:{create:x.items}},include:{vendor:true,items:true}}))}catch(e){next(e)}});

app.get('/api/po',auth,companyScope,async(req,res,next)=>{try{res.json(await prisma.purchaseOrder.findMany({where:{companyId:req.user.companyId},include:{vendor:true,site:true,items:{include:{material:true}}},orderBy:{orderDate:'desc'}}))}catch(e){next(e)}});
app.post('/api/po',auth,companyScope,role('PROCUREMENT'),async(req,res,next)=>{try{const x=z.object({siteId:z.string(),vendorId:z.string(),prId:z.string().optional(),items:z.array(z.object({materialId:z.string(),orderedQty:z.coerce.number().positive(),rate:z.coerce.number().nonnegative()})).min(1),tax:z.coerce.number().nonnegative().default(0)}).parse(req.body);const subtotal=x.items.reduce((s,i)=>s+i.orderedQty*i.rate,0);const r=await prisma.purchaseOrder.create({data:{companyId:req.user.companyId,siteId:x.siteId,vendorId:x.vendorId,prId:x.prId,number:`PO-${new Date().getFullYear()}-${Date.now().toString().slice(-7)}`,status:'APPROVED',subtotal,tax:x.tax,total:subtotal+x.tax,items:{create:x.items}},include:{vendor:true,site:true,items:true}});await audit(req,'CREATE','PurchaseOrder',r.id,null,r);res.status(201).json(r)}catch(e){next(e)}});
app.patch('/api/po/:id',auth,companyScope,role('PROCUREMENT'),async(req,res,next)=>{try{const x=z.object({status:z.enum(['DRAFT','PENDING','APPROVED','REJECTED','SENT','PARTIAL','CLOSED','CANCELLED']).optional()}).parse(req.body);res.json(await prisma.purchaseOrder.updateMany({where:{id:req.params.id,companyId:req.user.companyId},data:x}))}catch(e){next(e)}});

app.get('/api/grn',auth,companyScope,async(req,res,next)=>{try{res.json(await prisma.gRN.findMany({where:{companyId:req.user.companyId},include:{po:true,site:true,items:{include:{material:true}}},orderBy:{receivedAt:'desc'}}))}catch(e){next(e)}});
app.post('/api/grn',auth,companyScope,role('SITE_ENGINEER','SITE_STORE'),async(req,res,next)=>{try{const x=z.object({poId:z.string(),items:z.array(z.object({materialId:z.string(),receivedQty:z.coerce.number().positive(),rejectedQty:z.coerce.number().nonnegative().default(0)})).min(1)}).parse(req.body);const po=await prisma.purchaseOrder.findFirst({where:{id:x.poId,companyId:req.user.companyId},include:{items:true}});if(!po)return res.status(404).json({error:'PO not found'});const map=new Map(po.items.map(i=>[i.materialId,i]));for(const i of x.items){const l=map.get(i.materialId);if(!l||i.receivedQty>num(l.orderedQty)-num(l.receivedQty)||i.rejectedQty>i.receivedQty)throw new Error('Invalid received quantity')}const r=await prisma.$transaction(async tx=>{const g=await tx.gRN.create({data:{companyId:req.user.companyId,siteId:po.siteId,poId:po.id,number:`GRN-${new Date().getFullYear()}-${Date.now().toString().slice(-7)}`,status:'APPROVED',items:{create:x.items}},include:{items:true,po:true}});for(const i of x.items){const l=map.get(i.materialId);await tx.pOItem.update({where:{id:l.id},data:{receivedQty:{increment:i.receivedQty}}});const accepted=i.receivedQty-i.rejectedQty;if(accepted>0)await tx.stock.upsert({where:{siteId_materialId:{siteId:po.siteId,materialId:i.materialId}},create:{siteId:po.siteId,materialId:i.materialId,quantity:accepted},update:{quantity:{increment:accepted}}})}return g});await audit(req,'CREATE','GRN',r.id,null,r);res.status(201).json(r)}catch(e){next(e)}});

app.get('/api/mrn',auth,companyScope,async(req,res,next)=>{try{res.json(await prisma.mRN.findMany({where:{companyId:req.user.companyId},include:{site:true,items:{include:{material:true}}},orderBy:{createdAt:'desc'}}))}catch(e){next(e)}});
app.post('/api/mrn',auth,companyScope,role('SITE_ENGINEER','SITE_STORE'),async(req,res,next)=>{try{const x=z.object({siteId:z.string(),requestedBy:z.string(),requiredDate:z.coerce.date(),purpose:z.string().optional(),items:z.array(z.object({materialId:z.string(),quantity:z.coerce.number().positive()})).min(1)}).parse(req.body);const r=await prisma.mRN.create({data:{...x,companyId:req.user.companyId,number:`MRN-${new Date().getFullYear()}-${Date.now().toString().slice(-7)}`,status:'PENDING',items:{create:x.items}},include:{items:true,site:true}});await audit(req,'CREATE','MRN',r.id,null,r);res.status(201).json(r)}catch(e){next(e)}});
app.post('/api/mrn/:id/issue',auth,companyScope,role('SITE_STORE','SITE_ENGINEER'),async(req,res,next)=>{try{const x=z.object({items:z.array(z.object({materialId:z.string(),issuedQty:z.coerce.number().positive()})).min(1)}).parse(req.body);const m=await prisma.mRN.findFirst({where:{id:req.params.id,companyId:req.user.companyId},include:{items:true}});if(!m)return res.status(404).json({error:'MRN not found'});const map=new Map(m.items.map(i=>[i.materialId,i]));const r=await prisma.$transaction(async tx=>{for(const i of x.items){const l=map.get(i.materialId);if(!l||i.issuedQty>num(l.quantity)-num(l.issuedQty))throw new Error('Issue exceeds MRN quantity');const s=await tx.stock.findUnique({where:{siteId_materialId:{siteId:m.siteId,materialId:i.materialId}}});if(!s||num(s.quantity)<i.issuedQty)throw new Error('Insufficient stock');await tx.mRNItem.update({where:{id:l.id},data:{issuedQty:{increment:i.issuedQty}}});await tx.stock.update({where:{id:s.id},data:{quantity:{decrement:i.issuedQty}}})}return tx.mRN.findUnique({where:{id:m.id},include:{items:true}})});if(r.items.every(i=>num(i.issuedQty)>=num(i.quantity)))await prisma.mRN.update({where:{id:m.id},data:{status:'CLOSED'}});await audit(req,'ISSUE','MRN',m.id,m,r);res.json(r)}catch(e){next(e)}});
app.get('/api/stock',auth,companyScope,async(req,res,next)=>{try{res.json(await prisma.stock.findMany({where:{site:{companyId:req.user.companyId}},include:{site:true,material:true},orderBy:{site:{name:'asc'}}}))}catch(e){next(e)}});

app.get('/api/invoices',auth,companyScope,role('ACCOUNTS','MANAGEMENT'),async(req,res,next)=>{try{res.json(await prisma.invoice.findMany({where:{companyId:req.user.companyId},include:{vendor:true,po:true,payments:true},orderBy:{dueDate:'asc'}}))}catch(e){next(e)}});
app.post('/api/invoices',auth,companyScope,role('ACCOUNTS'),async(req,res,next)=>{try{const x=z.object({vendorId:z.string(),poId:z.string().optional(),number:z.string().min(1),invoiceDate:z.coerce.date(),dueDate:z.coerce.date().optional(),amount:z.coerce.number().positive()}).parse(req.body);const r=await prisma.invoice.create({data:{...x,companyId:req.user.companyId,status:'PENDING'}});await audit(req,'CREATE','Invoice',r.id,null,r);res.status(201).json(r)}catch(e){next(e)}});
app.patch('/api/invoices/:id',auth,companyScope,role('ACCOUNTS'),async(req,res,next)=>{try{const x=z.object({status:z.enum(['PENDING','APPROVED','REJECTED','PARTIAL','CLOSED','CANCELLED']).optional(),dueDate:z.coerce.date().optional()}).parse(req.body);res.json(await prisma.invoice.updateMany({where:{id:req.params.id,companyId:req.user.companyId},data:x}))}catch(e){next(e)}});
app.get('/api/payments',auth,companyScope,role('ACCOUNTS','MANAGEMENT'),async(req,res,next)=>{try{res.json(await prisma.payment.findMany({where:{companyId:req.user.companyId},include:{vendor:true,invoice:true},orderBy:{paidAt:'desc'}}))}catch(e){next(e)}});
app.post('/api/payments',auth,companyScope,role('ACCOUNTS'),async(req,res,next)=>{try{const x=z.object({vendorId:z.string().optional(),invoiceId:z.string().optional(),amount:z.coerce.number().positive(),method:z.enum(['BANK','CASH','UPI','CHEQUE','OTHER']),reference:z.string().optional()}).parse(req.body);const r=await prisma.$transaction(async tx=>{const p=await tx.payment.create({data:{...x,companyId:req.user.companyId}});if(x.invoiceId){const inv=await tx.invoice.findUnique({where:{id:x.invoiceId}});const paid=num(inv?.paidAmount)+x.amount;await tx.invoice.update({where:{id:x.invoiceId},data:{paidAmount:{increment:x.amount},status:paid>=num(inv.amount)?'CLOSED':'PARTIAL'}})}return p});await audit(req,'CREATE','Payment',r.id,null,r);res.status(201).json(r)}catch(e){next(e)}});
app.get('/api/expenses',auth,companyScope,role('ACCOUNTS','MANAGEMENT'),async(req,res,next)=>{try{res.json(await prisma.expense.findMany({where:{companyId:req.user.companyId},include:{site:true},orderBy:{expenseDate:'desc'}}))}catch(e){next(e)}});
app.post('/api/expenses',auth,companyScope,role('ACCOUNTS'),async(req,res,next)=>{try{const x=z.object({siteId:z.string().optional(),category:z.string(),description:z.string(),amount:z.coerce.number().positive(),expenseDate:z.coerce.date()}).parse(req.body);const r=await prisma.expense.create({data:{...x,companyId:req.user.companyId,status:'PENDING'}});await audit(req,'CREATE','Expense',r.id,null,r);res.status(201).json(r)}catch(e){next(e)}});

app.get('/api/tasks',auth,companyScope,role('SITE_ENGINEER','MANAGEMENT'),async(req,res,next)=>{try{res.json(await prisma.siteTask.findMany({where:{companyId:req.user.companyId},include:{site:true},orderBy:{createdAt:'desc'}}))}catch(e){next(e)}});
app.post('/api/tasks',auth,companyScope,role('SITE_ENGINEER'),async(req,res,next)=>{try{const x=z.object({siteId:z.string(),title:z.string().min(2),description:z.string().optional(),assignedTo:z.string().optional(),priority:z.string().default('NORMAL'),dueDate:z.coerce.date().optional()}).parse(req.body);res.status(201).json(await prisma.siteTask.create({data:{...x,companyId:req.user.companyId,status:'PENDING'}}))}catch(e){next(e)}});
app.patch('/api/tasks/:id',auth,companyScope,role('SITE_ENGINEER'),async(req,res,next)=>{try{const x=z.object({status:z.enum(['PENDING','APPROVED','REJECTED','CANCELLED','CLOSED']).optional(),assignedTo:z.string().optional(),priority:z.string().optional()}).parse(req.body);res.json(await prisma.siteTask.updateMany({where:{id:req.params.id,companyId:req.user.companyId},data:x}))}catch(e){next(e)}});

app.get('/api/employees/attendance',auth,companyScope,role('HR','MANAGEMENT'),async(req,res,next)=>{try{const w={employee:{companyId:req.user.companyId}};if(req.query.date)w.date=dateOnly(req.query.date);res.json(await prisma.employeeAttendance.findMany({where:w,include:{employee:true},orderBy:{date:'desc'}}))}catch(e){next(e)}});
app.post('/api/employees/:id/attendance',auth,companyScope,role('HR'),async(req,res,next)=>{try{const x=z.object({date:z.coerce.date(),status:z.enum(['PRESENT','ABSENT','HALF_DAY','LEAVE','WEEK_OFF']),inTime:z.coerce.date().optional(),outTime:z.coerce.date().optional(),remarks:z.string().optional()}).parse(req.body);res.status(201).json(await prisma.employeeAttendance.upsert({where:{employeeId_date:{employeeId:req.params.id,date:dateOnly(x.date)}},update:{...x,date:dateOnly(x.date)},create:{employeeId:req.params.id,...x,date:dateOnly(x.date)}}))}catch(e){next(e)}});
app.get('/api/labour/attendance',auth,companyScope,role('HR','SITE_ENGINEER','SITE_STORE','MANAGEMENT'),async(req,res,next)=>{try{const w={labour:{companyId:req.user.companyId}};if(req.query.siteId)w.siteId=req.query.siteId;res.json(await prisma.labourAttendance.findMany({where:w,include:{labour:true,site:true},orderBy:{date:'desc'}}))}catch(e){next(e)}});
app.post('/api/labour/attendance',auth,companyScope,role('HR','SITE_ENGINEER','SITE_STORE'),async(req,res,next)=>{try{const x=z.object({labourId:z.string(),siteId:z.string(),date:z.coerce.date(),status:z.enum(['PRESENT','ABSENT','HALF_DAY','LEAVE','WEEK_OFF']),units:z.coerce.number().nonnegative().optional(),overtimeHours:z.coerce.number().nonnegative().optional(),remarks:z.string().optional()}).parse(req.body);res.status(201).json(await prisma.labourAttendance.upsert({where:{labourId_siteId_date:{labourId:x.labourId,siteId:x.siteId,date:dateOnly(x.date)}},update:{...x,date:dateOnly(x.date)},create:{...x,date:dateOnly(x.date)}}))}catch(e){next(e)}});

app.get('/api/approvals',auth,companyScope,async(req,res,next)=>{try{res.json(await prisma.approval.findMany({where:{user:{companyId:req.user.companyId}},include:{user:{select:{id:true,name:true,email:true,role:true}}},orderBy:{createdAt:'desc'}}))}catch(e){next(e)}});
app.post('/api/approvals',auth,companyScope,async(req,res,next)=>{try{const x=z.object({entityType:z.string(),entityId:z.string(),status:z.enum(['PENDING','APPROVED','REJECTED']),comment:z.string().optional()}).parse(req.body);res.status(201).json(await prisma.approval.create({data:{...x,userId:req.user.userId}}))}catch(e){next(e)}});
app.get('/api/audit',auth,companyScope,role('ADMIN','MANAGEMENT'),async(req,res,next)=>{try{res.json(await prisma.auditLog.findMany({where:{companyId:req.user.companyId},include:{user:{select:{name:true,email:true,role:true}}},orderBy:{createdAt:'desc'},take:500}))}catch(e){next(e)}});

function csv(rows){if(!rows.length)return '';const keys=Object.keys(rows[0]);return [keys.join(','),...rows.map(r=>keys.map(k=>JSON.stringify(r[k]??'')).join(','))].join('\n')}
app.get('/api/reports/summary',auth,companyScope,role('ADMIN','MANAGEMENT','PROCUREMENT','ACCOUNTS','HR','SITE_ENGINEER','SITE_STORE'),async(req,res,next)=>{try{const c=req.user.companyId;const [vendors,materials,prs,pos,inv,expenses,employees,labour,stock]=await Promise.all([prisma.vendor.count({where:{companyId:c,active:true}}),prisma.material.count({where:{companyId:c,active:true}}),prisma.purchaseRequisition.count({where:{companyId:c}}),prisma.purchaseOrder.aggregate({where:{companyId:c},_sum:{total:true}}),prisma.invoice.aggregate({where:{companyId:c},_sum:{amount:true,paidAmount:true}}),prisma.expense.aggregate({where:{companyId:c},_sum:{amount:true}}),prisma.employee.count({where:{companyId:c,active:true}}),prisma.labour.count({where:{companyId:c,active:true}}),prisma.stock.aggregate({where:{site:{companyId:c}},_sum:{quantity:true}})]);res.json({vendors,materials,prs,totalPO:num(pos._sum.total),invoiceAmount:num(inv._sum.amount),paidAmount:num(inv._sum.paidAmount),expenses:num(expenses._sum.amount),employees,labour,stockQty:num(stock._sum.quantity),generatedAt:new Date().toISOString()})}catch(e){next(e)}});
app.get('/api/reports/generate',auth,companyScope,role('ADMIN','MANAGEMENT','PROCUREMENT','ACCOUNTS','HR','SITE_ENGINEER','SITE_STORE'),async(req,res,next)=>{try{const type=String(req.query.type||'dashboard');const c=req.user.companyId;let rows=[];if(type==='vendors')rows=(await prisma.vendor.findMany({where:{companyId:c},select:{name:true,gstin:true,email:true,phone:true,paymentDays:true,rating:true,active:true}}));else if(type==='materials')rows=(await prisma.material.findMany({where:{companyId:c},select:{code:true,name:true,category:true,unit:true,gstRate:true,reorderLevel:true,active:true}}));else if(type==='employees')rows=(await prisma.employee.findMany({where:{companyId:c},select:{employeeCode:true,name:true,email:true,phone:true,designation:true,employmentType:true,salary:true,active:true}}));else if(type==='invoices')rows=(await prisma.invoice.findMany({where:{companyId:c},include:{vendor:true},select:{number:true,invoiceDate:true,dueDate:true,amount:true,paidAmount:true,status:true,vendor:true}})).map(x=>({...x,vendor:x.vendor?.name}));else if(type==='audit')rows=(await prisma.auditLog.findMany({where:{companyId:c},include:{user:true},orderBy:{createdAt:'desc'},take:1000})).map(x=>({createdAt:x.createdAt,action:x.action,entityType:x.entityType,entityId:x.entityId,user:x.user?.name}));else rows=[await prisma.purchaseOrder.aggregate({where:{companyId:c},_sum:{total:true}})];res.setHeader('Content-Type','text/csv');res.setHeader('Content-Disposition',`attachment; filename="ezyprocure-${type}-${Date.now()}.csv"`);res.send(csv(rows))}catch(e){next(e)}});

app.use((err,_req,res,_next)=>{console.error(err);if(err?.name==='ZodError')return res.status(400).json({error:'Validation failed',details:err.issues});if(err?.code==='P2002')return res.status(409).json({error:'A record with the same unique value already exists'});res.status(500).json({error:err?.message||'Internal server error'})});
const port=Number(process.env.PORT||4000);const server=app.listen(port,()=>console.log(`EzyProcure Advanced API listening on ${port}`));process.on('SIGTERM',()=>server.close(async()=>{await prisma.$disconnect();process.exit(0)}));