import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import { PrismaClient } from '@prisma/client';
import { z } from 'zod';

const app = express();
const prisma = new PrismaClient();
app.use(helmet());
const configuredOrigins = (process.env.FRONTEND_URL || '').split(',').map(v=>v.trim().replace(/\/$/,'')).filter(Boolean);
const defaultOrigins = ['https://procurement.vaqutecalifornia.com','https://vaqutecalifornia.com','https://www.vaqutecalifornia.com','https://darkmoonknight.github.io'];
const allowed = new Set([...defaultOrigins,...configuredOrigins]);
app.use(cors({origin:(origin,cb)=>{if(!origin||allowed.has('*')||allowed.has(origin.replace(/\/$/,''))) return cb(null,true); cb(null,false);},credentials:true}));
app.use(express.json({limit:'4mb'}));

const signToken = user => jwt.sign({userId:user.id,companyId:user.companyId,role:user.role,departmentId:user.departmentId||null,email:user.email},process.env.JWT_SECRET,{expiresIn:process.env.JWT_EXPIRES_IN||'12h'});
const auth = (req,res,next)=>{const token=req.headers.authorization?.replace(/^Bearer\s+/i,'');if(!token)return res.status(401).json({error:'Authentication required'});try{req.user=jwt.verify(token,process.env.JWT_SECRET);next();}catch{return res.status(401).json({error:'Invalid or expired token'});}};
const companyScope=(req,res,next)=>req.user?.companyId?next():res.status(403).json({error:'Company scope missing'});
const role=(...roles)=>(req,res,next)=>roles.includes(req.user?.role)||req.user?.role==='ADMIN'?next():res.status(403).json({error:'Department access denied'});
const num=v=>Number(v||0);
const dateOnly=v=>{const d=new Date(v);d.setHours(0,0,0,0);return d;};
async function audit(req,action,entityType,entityId,before=null,after=null){try{await prisma.auditLog.create({data:{companyId:req.user.companyId,userId:req.user.userId,action,entityType,entityId,beforeJson:before?JSON.stringify(before):null,afterJson:after?JSON.stringify(after):null,ipAddress:req.ip}});}catch(e){console.error('audit',e.message)}}

app.get('/',(_req,res)=>res.json({ok:true,service:'ezyprocure-api',status:'online'}));
app.get('/health',async(_req,res)=>{try{await prisma.$queryRaw`SELECT 1`;res.json({ok:true,service:'ezyprocure-api',database:'connected'});}catch{res.status(503).json({ok:false,service:'ezyprocure-api',database:'unavailable'});}});
app.get('/api/health',async(_req,res)=>{try{await prisma.$queryRaw`SELECT 1`;res.json({ok:true,service:'ezyprocure-api',database:'connected'});}catch{res.status(503).json({ok:false,service:'ezyprocure-api',database:'unavailable'});}});

app.post('/api/auth/login',async(req,res,next)=>{try{const {email,password}=z.object({email:z.string().email(),password:z.string().min(1)}).parse(req.body);const user=await prisma.user.findUnique({where:{email:email.toLowerCase()},include:{company:true,department:true}});if(!user||!user.active||!(await bcrypt.compare(password,user.passwordHash)))return res.status(401).json({error:'Invalid email or password'});res.json({token:signToken(user),user:{id:user.id,name:user.name,email:user.email,role:user.role,department:user.department?.name||'Owner / Administration',departmentId:user.departmentId,companyId:user.companyId},company:{id:user.company.id,name:user.company.name}});}catch(e){next(e)}});
app.get('/api/auth/me',auth,companyScope,async(req,res,next)=>{try{const user=await prisma.user.findFirst({where:{id:req.user.userId,companyId:req.user.companyId,active:true},include:{department:true,company:true}});if(!user)return res.status(401).json({error:'User not found'});res.json({id:user.id,name:user.name,email:user.email,role:user.role,department:user.department?.name||'Owner / Administration',departmentId:user.departmentId,companyId:user.companyId,company:user.company.name});}catch(e){next(e)}});

app.get('/api/me/permissions',auth,companyScope,async(req,res)=>{const r=req.user.role;const map={ADMIN:['*'],MANAGEMENT:['dashboard','reports','approvals','sites','vendors','procurement','accounts','hr','site'],PROCUREMENT:['dashboard','sites','materials','vendors','pr','rfq','quotes','po','reports'],ACCOUNTS:['dashboard','invoices','payments','expenses','vendors','reports','approvals'],HR:['dashboard','employees','attendance','labour','reports'],SITE_ENGINEER:['dashboard','sites','tasks','materials','mrn','grn','stock','labour','labour-attendance'],SITE_STORE:['dashboard','sites','materials','mrn','grn','stock','labour','labour-attendance'],};res.json({role:r,permissions:map[r]||[]});});

app.get('/api/modules',auth,companyScope,(_req,res)=>res.json({sites:true,materials:true,vendors:true,pr:true,rfq:true,quotes:true,po:true,grn:true,mrn:true,stock:true,invoices:true,payments:true,expenses:true,employees:true,attendance:true,labour:true,labourAttendance:true,tasks:true,reports:true,approvals:true}));
app.get('/api/dashboard',auth,companyScope,async(req,res,next)=>{try{const c=req.user.companyId;const [prs,rfqs,pos,grns,mrns,invoices,vendors,employees,labour,expenses]=await Promise.all([prisma.purchaseRequisition.count({where:{companyId:c,status:{in:['DRAFT','PENDING']}}}),prisma.rFQ.count({where:{companyId:c,status:{in:['DRAFT','SENT']}}}),prisma.purchaseOrder.count({where:{companyId:c,status:{in:['DRAFT','APPROVED','SENT','PARTIAL']}}}),prisma.gRN.count({where:{companyId:c,status:{in:['DRAFT','APPROVED']}}}),prisma.mRN.count({where:{companyId:c,status:{in:['DRAFT','PENDING','APPROVED']}}}),prisma.invoice.count({where:{companyId:c,status:{in:['PENDING','PARTIAL']}}}),prisma.vendor.count({where:{companyId:c,active:true}}),prisma.employee.count({where:{companyId:c,active:true}}),prisma.labour.count({where:{companyId:c,active:true}}),prisma.expense.aggregate({where:{companyId:c},_sum:{amount:true}})]);res.json({pendingPR:prs,pendingRFQ:rfqs,openPO:pos,openGRN:grns,pendingMRN:mrns,pendingInvoices:invoices,activeVendors:vendors,employees,activeLabour:labour,totalExpenses:num(expenses._sum.amount)});}catch(e){next(e)}});

app.get('/api/departments',auth,companyScope,async(req,res,next)=>{try{res.json(await prisma.department.findMany({where:{companyId:req.user.companyId,active:true},orderBy:{name:'asc'}}))}catch(e){next(e)}});
app.get('/api/sites',auth,companyScope,async(req,res,next)=>{try{res.json(await prisma.site.findMany({where:{companyId:req.user.companyId,active:true},orderBy:{name:'asc'}}))}catch(e){next(e)}});
app.post('/api/sites',auth,companyScope,role('SITE_ENGINEER','MANAGEMENT'),async(req,res,next)=>{try{const input=z.object({code:z.string().min(2),name:z.string().min(2),location:z.string().optional(),manager:z.string().optional()}).parse(req.body);const site=await prisma.site.create({data:{...input,companyId:req.user.companyId}});await audit(req,'CREATE','Site',site.id,null,site);res.status(201).json(site)}catch(e){next(e)}});
app.get('/api/materials',auth,companyScope,async(req,res,next)=>{try{res.json(await prisma.material.findMany({where:{companyId:req.user.companyId,active:true},orderBy:{name:'asc'}}))}catch(e){next(e)}});
app.get('/api/vendors',auth,companyScope,async(req,res,next)=>{try{res.json(await prisma.vendor.findMany({where:{companyId:req.user.companyId,active:true},orderBy:{name:'asc'}}))}catch(e){next(e)}});

app.get('/api/employees',auth,companyScope,role('HR','MANAGEMENT'),async(req,res,next)=>{try{res.json(await prisma.employee.findMany({where:{companyId:req.user.companyId,active:true},include:{department:true},orderBy:{name:'asc'}}))}catch(e){next(e)}});
app.post('/api/employees',auth,companyScope,role('HR'),async(req,res,next)=>{try{const input=z.object({employeeCode:z.string(),name:z.string().min(2),email:z.string().email().optional().or(z.literal('')),phone:z.string().optional(),designation:z.string().optional(),departmentId:z.string().optional(),employmentType:z.string().default('FULL_TIME'),salary:z.coerce.number().nonnegative().optional(),joiningDate:z.coerce.date().optional()}).parse(req.body);const emp=await prisma.employee.create({data:{...input,companyId:req.user.companyId,email:input.email||null}});await audit(req,'CREATE','Employee',emp.id,null,emp);res.status(201).json(emp)}catch(e){next(e)}});
app.post('/api/employees/:id/attendance',auth,companyScope,role('HR'),async(req,res,next)=>{try{const input=z.object({date:z.coerce.date(),status:z.enum(['PRESENT','ABSENT','HALF_DAY','LEAVE','WEEK_OFF']),inTime:z.coerce.date().optional(),outTime:z.coerce.date().optional(),remarks:z.string().optional()}).parse(req.body);const row=await prisma.employeeAttendance.upsert({where:{employeeId_date:{employeeId:req.params.id,date:dateOnly(input.date)}},update:input,create:{employeeId:req.params.id,...input,date:dateOnly(input.date)}});res.status(201).json(row)}catch(e){next(e)}});
app.get('/api/employees/attendance',auth,companyScope,role('HR','MANAGEMENT'),async(req,res,next)=>{try{const where={employee:{companyId:req.user.companyId}};if(req.query.date)where.date=dateOnly(req.query.date);res.json(await prisma.employeeAttendance.findMany({where,include:{employee:true},orderBy:{date:'desc'}}))}catch(e){next(e)}});

app.get('/api/labour',auth,companyScope,role('HR','SITE_ENGINEER','SITE_STORE','MANAGEMENT'),async(req,res,next)=>{try{res.json(await prisma.labour.findMany({where:{companyId:req.user.companyId,active:true},orderBy:{name:'asc'}}))}catch(e){next(e)}});
app.post('/api/labour',auth,companyScope,role('HR','SITE_STORE'),async(req,res,next)=>{try{const input=z.object({labourCode:z.string(),name:z.string().min(2),trade:z.string().optional(),contractor:z.string().optional(),phone:z.string().optional(),dailyRate:z.coerce.number().nonnegative().optional()}).parse(req.body);const row=await prisma.labour.create({data:{...input,companyId:req.user.companyId}});await audit(req,'CREATE','Labour',row.id,null,row);res.status(201).json(row)}catch(e){next(e)}});
app.post('/api/labour/attendance',auth,companyScope,role('HR','SITE_ENGINEER','SITE_STORE'),async(req,res,next)=>{try{const input=z.object({labourId:z.string(),siteId:z.string(),date:z.coerce.date(),status:z.enum(['PRESENT','ABSENT','HALF_DAY','LEAVE','WEEK_OFF']),units:z.coerce.number().nonnegative().optional(),overtimeHours:z.coerce.number().nonnegative().optional(),remarks:z.string().optional()}).parse(req.body);const labour=await prisma.labour.findFirst({where:{id:input.labourId,companyId:req.user.companyId}});const site=await prisma.site.findFirst({where:{id:input.siteId,companyId:req.user.companyId}});if(!labour||!site)return res.status(400).json({error:'Invalid labour or site'});const row=await prisma.labourAttendance.upsert({where:{labourId_siteId_date:{labourId:input.labourId,siteId:input.siteId,date:dateOnly(input.date)}},update:{status:input.status,units:input.units,overtimeHours:input.overtimeHours,remarks:input.remarks},create:{...input,date:dateOnly(input.date)}});res.status(201).json(row)}catch(e){next(e)}});
app.get('/api/labour/attendance',auth,companyScope,role('HR','SITE_ENGINEER','SITE_STORE','MANAGEMENT'),async(req,res,next)=>{try{const where={labour:{companyId:req.user.companyId}};if(req.query.siteId)where.siteId=req.query.siteId;if(req.query.date)where.date=dateOnly(req.query.date);res.json(await prisma.labourAttendance.findMany({where,include:{labour:true,site:true},orderBy:{date:'desc'}}))}catch(e){next(e)}});

const prSchema=z.object({siteId:z.string(),requestedBy:z.string(),requiredDate:z.coerce.date(),notes:z.string().optional(),items:z.array(z.object({materialId:z.string(),quantity:z.coerce.number().positive(),estimatedRate:z.coerce.number().nonnegative().optional()})).min(1)});
app.post('/api/pr',auth,companyScope,role('PROCUREMENT','SITE_ENGINEER','SITE_STORE'),async(req,res,next)=>{try{const input=prSchema.parse(req.body);const site=await prisma.site.findFirst({where:{id:input.siteId,companyId:req.user.companyId,active:true}});if(!site)return res.status(400).json({error:'Invalid site'});const number=`PR-${new Date().getFullYear()}-${Date.now().toString().slice(-7)}`;const pr=await prisma.purchaseRequisition.create({data:{...input,companyId:req.user.companyId,number,status:'PENDING',items:{create:input.items}} ,include:{items:true,site:true}});await audit(req,'CREATE','PurchaseRequisition',pr.id,null,pr);res.status(201).json(pr)}catch(e){next(e)}});
app.get('/api/pr',auth,companyScope,async(req,res,next)=>{try{res.json(await prisma.purchaseRequisition.findMany({where:{companyId:req.user.companyId},include:{items:{include:{material:true}},site:true},orderBy:{createdAt:'desc'}}))}catch(e){next(e)}});

app.post('/api/rfq',auth,companyScope,role('PROCUREMENT'),async(req,res,next)=>{try{const input=z.object({prId:z.string(),dueDate:z.coerce.date(),vendorIds:z.array(z.string()).min(1)}).parse(req.body);const pr=await prisma.purchaseRequisition.findFirst({where:{id:input.prId,companyId:req.user.companyId},include:{items:true}});if(!pr)return res.status(404).json({error:'PR not found'});const vendors=await prisma.vendor.findMany({where:{id:{in:input.vendorIds},companyId:req.user.companyId,active:true}});const rfq=await prisma.rFQ.create({data:{companyId:req.user.companyId,prId:pr.id,number:`RFQ-${new Date().getFullYear()}-${Date.now().toString().slice(-7)}`,dueDate:input.dueDate,status:'SENT',vendors:{create:vendors.map(v=>({vendorId:v.id}))}},include:{vendors:{include:{vendor:true}},pr:true}});await prisma.purchaseRequisition.update({where:{id:pr.id},data:{status:'APPROVED'}});await audit(req,'CREATE','RFQ',rfq.id,null,rfq);res.status(201).json(rfq)}catch(e){next(e)}});
app.get('/api/rfq',auth,companyScope,async(req,res,next)=>{try{res.json(await prisma.rFQ.findMany({where:{companyId:req.user.companyId},include:{pr:true,vendors:{include:{vendor:true}},quotes:{include:{vendor:true,items:true}}},orderBy:{dueDate:'asc'}}))}catch(e){next(e)}});
app.post('/api/quotes',auth,companyScope,role('PROCUREMENT'),async(req,res,next)=>{try{const input=z.object({rfqId:z.string(),vendorId:z.string(),quoteNo:z.string().optional(),freight:z.coerce.number().nonnegative().default(0),tax:z.coerce.number().nonnegative().default(0),items:z.array(z.object({materialId:z.string(),quantity:z.coerce.number().positive(),unitRate:z.coerce.number().nonnegative()})).min(1)}).parse(req.body);const rfq=await prisma.rFQ.findFirst({where:{id:input.rfqId,companyId:req.user.companyId}});const vendor=await prisma.vendor.findFirst({where:{id:input.vendorId,companyId:req.user.companyId}});if(!rfq||!vendor)return res.status(404).json({error:'RFQ or vendor not found'});const total=input.items.reduce((s,i)=>s+i.quantity*i.unitRate,0)+input.freight+input.tax;const q=await prisma.quote.create({data:{rfqId:rfq.id,vendorId:vendor.id,quoteNo:input.quoteNo,freight:input.freight,tax:input.tax,total,items:{create:input.items}} ,include:{vendor:true,items:true}});res.status(201).json(q)}catch(e){next(e)}});
app.get('/api/quotes',auth,companyScope,async(req,res,next)=>{try{res.json(await prisma.quote.findMany({where:{rfq:{companyId:req.user.companyId}},include:{vendor:true,rfq:true,items:{include:{material:true}}},orderBy:{total:'asc'}}))}catch(e){next(e)}});
app.post('/api/po',auth,companyScope,role('PROCUREMENT'),async(req,res,next)=>{try{const input=z.object({siteId:z.string(),vendorId:z.string(),prId:z.string().optional(),items:z.array(z.object({materialId:z.string(),orderedQty:z.coerce.number().positive(),rate:z.coerce.number().nonnegative()})).min(1),tax:z.coerce.number().nonnegative().default(0)}).parse(req.body);const subtotal=input.items.reduce((s,i)=>s+i.orderedQty*i.rate,0);const po=await prisma.purchaseOrder.create({data:{companyId:req.user.companyId,siteId:input.siteId,vendorId:input.vendorId,prId:input.prId,number:`PO-${new Date().getFullYear()}-${Date.now().toString().slice(-7)}`,status:'APPROVED',subtotal,tax:input.tax,total:subtotal+input.tax,items:{create:input.items}} ,include:{vendor:true,site:true,items:true}});await audit(req,'CREATE','PurchaseOrder',po.id,null,po);res.status(201).json(po)}catch(e){next(e)}});
app.get('/api/po',auth,companyScope,async(req,res,next)=>{try{res.json(await prisma.purchaseOrder.findMany({where:{companyId:req.user.companyId},include:{vendor:true,site:true,items:{include:{material:true}}},orderBy:{orderDate:'desc'}}))}catch(e){next(e)}});

const grnSchema=z.object({poId:z.string(),items:z.array(z.object({materialId:z.string(),receivedQty:z.coerce.number().positive(),rejectedQty:z.coerce.number().nonnegative().default(0)})).min(1)});
app.post('/api/grn',auth,companyScope,role('SITE_ENGINEER','SITE_STORE'),async(req,res,next)=>{try{const input=grnSchema.parse(req.body);const po=await prisma.purchaseOrder.findFirst({where:{id:input.poId,companyId:req.user.companyId},include:{items:true}});if(!po)return res.status(404).json({error:'PO not found'});const map=new Map(po.items.map(i=>[i.materialId,i]));for(const item of input.items){const line=map.get(item.materialId);if(!line||item.receivedQty>num(line.orderedQty)-num(line.receivedQty))return res.status(400).json({error:'Invalid GRN quantity'});}const grn=await prisma.$transaction(async tx=>{const created=await tx.gRN.create({data:{companyId:req.user.companyId,siteId:po.siteId,poId:po.id,number:`GRN-${new Date().getFullYear()}-${Date.now().toString().slice(-7)}`,status:'APPROVED',items:{create:input.items}},include:{items:true,po:true}});for(const item of input.items){const line=map.get(item.materialId);await tx.pOItem.update({where:{id:line.id},data:{receivedQty:{increment:item.receivedQty}}});const accepted=item.receivedQty-item.rejectedQty;if(accepted>0)await tx.stock.upsert({where:{siteId_materialId:{siteId:po.siteId,materialId:item.materialId}},create:{siteId:po.siteId,materialId:item.materialId,quantity:accepted},update:{quantity:{increment:accepted}}});}return created;});await audit(req,'CREATE','GRN',grn.id,null,grn);res.status(201).json(grn)}catch(e){next(e)}});
app.get('/api/grn',auth,companyScope,async(req,res,next)=>{try{res.json(await prisma.gRN.findMany({where:{companyId:req.user.companyId},include:{po:true,site:true,items:{include:{material:true}}},orderBy:{receivedAt:'desc'}}))}catch(e){next(e)}});

const mrnSchema=z.object({siteId:z.string(),requestedBy:z.string(),requiredDate:z.coerce.date(),purpose:z.string().optional(),items:z.array(z.object({materialId:z.string(),quantity:z.coerce.number().positive()})).min(1)});
app.post('/api/mrn',auth,companyScope,role('SITE_ENGINEER','SITE_STORE'),async(req,res,next)=>{try{const input=mrnSchema.parse(req.body);const site=await prisma.site.findFirst({where:{id:input.siteId,companyId:req.user.companyId}});if(!site)return res.status(400).json({error:'Invalid site'});const mrn=await prisma.mRN.create({data:{...input,companyId:req.user.companyId,number:`MRN-${new Date().getFullYear()}-${Date.now().toString().slice(-7)}`,status:'PENDING',items:{create:input.items}},include:{items:true,site:true}});await audit(req,'CREATE','MRN',mrn.id,null,mrn);res.status(201).json(mrn)}catch(e){next(e)}});
app.get('/api/mrn',auth,companyScope,async(req,res,next)=>{try{res.json(await prisma.mRN.findMany({where:{companyId:req.user.companyId},include:{site:true,items:{include:{material:true}}},orderBy:{createdAt:'desc'}}))}catch(e){next(e)}});
app.post('/api/mrn/:id/issue',auth,companyScope,role('SITE_STORE','SITE_ENGINEER'),async(req,res,next)=>{try{const input=z.object({items:z.array(z.object({materialId:z.string(),issuedQty:z.coerce.number().positive()})).min(1)}).parse(req.body);const mrn=await prisma.mRN.findFirst({where:{id:req.params.id,companyId:req.user.companyId},include:{items:true}});if(!mrn)return res.status(404).json({error:'MRN not found'});const smap=new Map(mrn.items.map(i=>[i.materialId,i]));const updated=await prisma.$transaction(async tx=>{for(const item of input.items){const line=smap.get(item.materialId);if(!line||item.issuedQty>num(line.quantity)-num(line.issuedQty))throw new Error('Issue exceeds MRN quantity');const stock=await tx.stock.findUnique({where:{siteId_materialId:{siteId:mrn.siteId,materialId:item.materialId}}});if(!stock||num(stock.quantity)<item.issuedQty)throw new Error('Insufficient stock');await tx.mRNItem.update({where:{id:line.id},data:{issuedQty:{increment:item.issuedQty}}});await tx.stock.update({where:{id:stock.id},data:{quantity:{decrement:item.issuedQty}}});}return tx.mRN.findUnique({where:{id:mrn.id},include:{items:true}})});await txSafeStatus(req,mrn.id,updated);res.json(updated)}catch(e){next(e)}});
async function txSafeStatus(req,id,current){try{const done=current.items.every(i=>num(i.issuedQty)>=num(i.quantity));if(done)await prisma.mRN.update({where:{id},data:{status:'CLOSED'}});await audit(req,'ISSUE','MRN',id,null,current)}catch(e){console.error(e.message)}}
app.get('/api/stock',auth,companyScope,role('SITE_ENGINEER','SITE_STORE','MANAGEMENT'),async(req,res,next)=>{try{res.json(await prisma.stock.findMany({where:{site:{companyId:req.user.companyId}},include:{site:true,material:true},orderBy:{site:{name:'asc'}}}))}catch(e){next(e)}});

app.get('/api/tasks',auth,companyScope,role('SITE_ENGINEER','MANAGEMENT'),async(req,res,next)=>{try{const where={companyId:req.user.companyId};if(req.query.siteId)where.siteId=req.query.siteId;res.json(await prisma.siteTask.findMany({where,include:{site:true},orderBy:{createdAt:'desc'}}))}catch(e){next(e)}});
app.post('/api/tasks',auth,companyScope,role('SITE_ENGINEER'),async(req,res,next)=>{try{const input=z.object({siteId:z.string(),title:z.string().min(2),description:z.string().optional(),assignedTo:z.string().optional(),priority:z.string().default('NORMAL'),dueDate:z.coerce.date().optional()}).parse(req.body);const task=await prisma.siteTask.create({data:{...input,companyId:req.user.companyId,status:'PENDING'}});res.status(201).json(task)}catch(e){next(e)}});
app.patch('/api/tasks/:id',auth,companyScope,role('SITE_ENGINEER'),async(req,res,next)=>{try{const input=z.object({status:z.enum(['PENDING','APPROVED','REJECTED','CANCELLED','CLOSED']).optional(),assignedTo:z.string().optional(),priority:z.string().optional()}).parse(req.body);const task=await prisma.siteTask.updateMany({where:{id:req.params.id,companyId:req.user.companyId},data:input});res.json(task)}catch(e){next(e)}});

app.get('/api/invoices',auth,companyScope,role('ACCOUNTS','MANAGEMENT'),async(req,res,next)=>{try{res.json(await prisma.invoice.findMany({where:{companyId:req.user.companyId},include:{vendor:true,po:true,payments:true},orderBy:{dueDate:'asc'}}))}catch(e){next(e)}});
app.post('/api/invoices',auth,companyScope,role('ACCOUNTS'),async(req,res,next)=>{try{const input=z.object({vendorId:z.string(),poId:z.string().optional(),number:z.string().min(1),invoiceDate:z.coerce.date(),dueDate:z.coerce.date().optional(),amount:z.coerce.number().positive()}).parse(req.body);const inv=await prisma.invoice.create({data:{...input,companyId:req.user.companyId,status:'PENDING'}});await audit(req,'CREATE','Invoice',inv.id,null,inv);res.status(201).json(inv)}catch(e){next(e)}});
app.get('/api/payments',auth,companyScope,role('ACCOUNTS','MANAGEMENT'),async(req,res,next)=>{try{res.json(await prisma.payment.findMany({where:{companyId:req.user.companyId},include:{vendor:true,invoice:true},orderBy:{paidAt:'desc'}}))}catch(e){next(e)}});
app.post('/api/payments',auth,companyScope,role('ACCOUNTS'),async(req,res,next)=>{try{const input=z.object({vendorId:z.string().optional(),invoiceId:z.string().optional(),amount:z.coerce.number().positive(),method:z.enum(['BANK','CASH','UPI','CHEQUE','OTHER']),reference:z.string().optional()}).parse(req.body);const p=await prisma.$transaction(async tx=>{const row=await tx.payment.create({data:{...input,companyId:req.user.companyId}});if(input.invoiceId)await tx.invoice.update({where:{id:input.invoiceId},data:{paidAmount:{increment:input.amount},status:'PARTIAL'}});return row;});res.status(201).json(p)}catch(e){next(e)}});
app.get('/api/expenses',auth,companyScope,role('ACCOUNTS','MANAGEMENT'),async(req,res,next)=>{try{res.json(await prisma.expense.findMany({where:{companyId:req.user.companyId},include:{site:true},orderBy:{expenseDate:'desc'}}))}catch(e){next(e)}});
app.post('/api/expenses',auth,companyScope,role('ACCOUNTS'),async(req,res,next)=>{try{const input=z.object({siteId:z.string().optional(),category:z.string(),description:z.string(),amount:z.coerce.number().positive(),expenseDate:z.coerce.date()}).parse(req.body);const row=await prisma.expense.create({data:{...input,companyId:req.user.companyId,status:'PENDING'}});res.status(201).json(row)}catch(e){next(e)}});

app.get('/api/approvals',auth,companyScope,async(req,res,next)=>{try{res.json(await prisma.approval.findMany({where:{user:{companyId:req.user.companyId}},include:{user:{select:{id:true,name:true,email:true,role:true}}},orderBy:{createdAt:'desc'}}))}catch(e){next(e)}});
app.post('/api/approvals',auth,companyScope,async(req,res,next)=>{try{const input=z.object({entityType:z.string(),entityId:z.string(),status:z.enum(['PENDING','APPROVED','REJECTED']),comment:z.string().optional()}).parse(req.body);const a=await prisma.approval.create({data:{...input,userId:req.user.userId}});res.status(201).json(a)}catch(e){next(e)}});
app.get('/api/audit',auth,companyScope,role('ADMIN','MANAGEMENT'),async(req,res,next)=>{try{res.json(await prisma.auditLog.findMany({where:{companyId:req.user.companyId},include:{user:{select:{name:true,email:true,role:true}}},orderBy:{createdAt:'desc'},take:200}))}catch(e){next(e)}});

app.use((err,_req,res,_next)=>{console.error(err);if(err?.name==='ZodError')return res.status(400).json({error:'Validation failed',details:err.issues});res.status(500).json({error:err?.message||'Internal server error'});});
const port=Number(process.env.PORT||4000);const server=app.listen(port,()=>console.log(`EzyProcure Enterprise API listening on ${port}`));process.on('SIGTERM',async()=>{server.close(async()=>{await prisma.$disconnect();process.exit(0)})});
